baseURL: https://ahgamut.github.io
languageCode: 'en-us'
title: 'Blog Needs a Name'
theme: "etch"

frontmatter:
  date:
    - :filename
    - date
    - publishDate

permalinks:
  posts: /:year/:month/:day/:slug


enableInlineShortcodes: true
pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  highlight: true
  dark: "off"
  description: "Gautham's Blog"
  copyright: "Copyright Â© 2022 Gautham Venkatasubramanian"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

menu:
  main:
    - identifier: "About"
      name: "About"
      title: "About"
      url: "/about/"
      weight: 30
